#! /usr/bin/env php

<?php
use Wbs\Commands\InstallFramework;
use Symfony\Component\Console\Application;
use Wbs\Commands\InstallShopScript;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Application('Webasyst install tool', '1.1.1');

$app->add(new InstallFramework);
$app->add(new InstallShopScript);

$app->run();
