#! /usr/bin/env php

<?php
use Acme\Commands\InstallFramework;
use Symfony\Component\Console\Application;

require "vendor/autoload.php";

$app = new Application('Webasyst install tool', '1.0');

$app->add(new InstallFramework);

$app->run();
